#production
deployment:
  user: diego
  from: ./
  to: /home/diego/show-me-the-issue
  excludes:
releases:
  enabled: true
  max: 10
  symlink: current
  directory: releases
hosts:
	- dev03.case-dev.com
tasks:
  pre-deploy:
  on-deploy:
  post-release:
  post-deploy:
