<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'GithubConnector\Module'        => __DIR__ . '/Module.php',
  'GithubConnector\GithubService' => __DIR__ . '/src/GithubConnector/GithubService.php',
  'GithubConnector\IssueHydrator' => __DIR__ . '/src/GithubConnector/IssueHydrator.php',
);
