language: php

before_script:
  - composer self-update
  - composer install -vv

script:
  - ./vendor/bin/php-cs-fixer -v fix module --dry-run --config-file ./.php_cs
  - ./runtests.sh

php:
  - 5.4
  - 5.5

notifications:
  email: false