<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ShowMeTheIssue\Module'                        => __DIR__ . '/Module.php',
  'ShowMeTheIssue\Controller\ShowController'     => __DIR__ . '/src/ShowMeTheIssue/Controller/ShowController.php',
  'ShowMeTheIssue\Entity\IssueAbstract'          => __DIR__ . '/src/ShowMeTheIssue/Entity/IssueAbstract.php',
  'ShowMeTheIssue\Repo\RepoInterface'            => __DIR__ . '/src/ShowMeTheIssue/Repo/RepoInterface.php',
  'ShowMeTheIssue\Service\ShowMeTheIssueService' => __DIR__ . '/src/ShowMeTheIssue/Service/ShowMeTheIssueService.php',
);
