<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ShowMeTheIssue\Module'                        => __DIR__ . '/Module.php',
    'ShowMeTheIssue\Controller\ShowController' => __DIR__ . '/src/ShowMeTheIssue/Controller/ShowController.php',
   
);
