<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BitbucketConnector\Module'           => __DIR__ . '/Module.php',
  'BitbucketConnector\BitbucketService' => __DIR__ . '/src/BitbucketConnector/BitbucketService.php',
  'BitbucketConnector\IssueHydrator'    => __DIR__ . '/src/BitbucketConnector/IssueHydrator.php',
);
